Vagrant.configure("2") do |config|
    
    config.vm.define:server2012 do |teste_config|
        teste_config.vm.hostname = "server2012"
        teste_config.vm.box = "addle/windows-server-2012-r2"
        teste_config.vm.box_version = "1.20170205.1"
        teste_config.vbguest.auto_update = false
        #teste_config.vbguest.installer_options = { allow_kernel_upgrade: true }
        teste_config.vm.network "private_network", ip: "192.168.14.103"
        #teste_config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
        #teste_config.vm.provision "shell", path: "provision.sh"
        config.vm.provider:virtualbox do |v|
            v.memory = 2900
            v.cpus = 1

            #config.vm.synced_folder ".", "/vagrant", type: "nfs"
        end
    
    
    end
    
    
end